services:
  chatooha_chat:
    build:
      context: .
    container_name: chatooha_chat
    volumes:
      - './app:/app'
    working_dir: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PORT=${PORT:-8080}
    ports:
      - "${PORT:-8099}:${PORT:-8099}"
