services:
  print_stream_local_ollama:
    build:
      context: .
    container_name: print_stream_local_ollama
    volumes:
      - './app:/app'
    working_dir: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PORT=${PORT:-8080}
    ports:
      - "${PORT:-8099}:${PORT:-8099}"
